from django.conf.urls import patterns, include, url
from django.contrib import admin
from appxiencias.admin import cmyvaladmin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xiencias.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

		url(r'^admin/', include(admin.site.urls)),
		url(r'^cmyvaladmin/', cmyvaladmin.urls), 
		url(r'^$', 'appxiencias.views.ingresar'),
		url(r'^servicio/$', 'appxiencias.views.servicio'),
		url(r'^ingresar/$', 'appxiencias.views.ingresar'), 
		url(r'^pushin/$', 'appxiencias.views.pushin'), 
		url(r'^salir/$', 'appxiencias.views.salir'),
		url(r'^consulta/$', 'appxiencias.views.consulta'),
		url(r'^consultablaster/(\w+)/$', 'appxiencias.views.consultablaster'),
		url(r'^consultalote/$', 'appxiencias.views.consultalote'),
		url(r'^clientes/$', 'appxiencias.views.clientes'),
		url(r'^servicios/(\w+)/$', 'appxiencias.views.servicios'),
		url(r'^lote/(\w+)/(\w+)/$', 'appxiencias.views.lote'),
		url(r'^verlote/$', 'appxiencias.views.verlote'),
		url(r'^verlotesms/$', 'appxiencias.views.verlotesms'),
		url(r'^activar/(\w+)/$', 'appxiencias.views.activar'),
		url(r'^desactivar/(\w+)/$', 'appxiencias.views.desactivar'),
		url(r'^introduccion/$', 'appxiencias.views.introduccion'),
		url(r'^user/$', 'appxiencias.views.user'),
		url(r'^docconsulta/$', 'appxiencias.views.docconsulta'),
		url(r'^voip/single$', 'appxiencias.views.voipsingle'),
		url(r'^doccarga/$', 'appxiencias.views.doccarga'),
		url(r'^mlote/$', 'appxiencias.views.mlote'),
		url(r'^cargabase/$', 'appxiencias.views.cargabase'),
		url(r'^uploadbase/$', 'appxiencias.views.uploadbase'),
		url(r'^reporte/$', 'appxiencias.views.reporte'),
		url(r'^buscar/$', 'appxiencias.views.buscar'),
		url(r'^menu/$', 'appxiencias.views.menu'),
		url(r'^blaster/$', 'appxiencias.views.blaster'),
		url(r'^consultablaster/$', 'appxiencias.views.consultablaster'),
		url(r'^consultaloteblaster/$', 'appxiencias.views.consultaloteblaster'),
		url(r'^lotesblaster/$', 'appxiencias.views.lotesblaster'),
		url(r'^querylote/(\w+)/(\w+)/$', 'appxiencias.views.querylote'),
		url(r'^querylotesms/(\w+)/(\w+)/(\d+)/$', 'appxiencias.views.querylotesms'),
		url(r'^lanza/$', 'appxiencias.views.lanza'),
		url(r'^apaga/$', 'appxiencias.views.apaga'),
		url(r'^configuracion/$', 'appxiencias.views.configuracion'),
		url(r'^descargacsv/$', 'appxiencias.views.descargacsv'),
		url(r'^descargacsvlote/(\w+)/$', 'appxiencias.views.descargacsvlote'),
		url(r'^lotes/$', 'appxiencias.views.lotes'),
		url(r'^enviarlote/(\w+)/$', 'appxiencias.views.enviarlote'),
		url(r'^cancelarlote/(\w+)/$', 'appxiencias.views.cancelarlote'),
		url(r'^cancelarlotesms/(\w+)/$', 'appxiencias.views.cancelarlotesms'),
		url(r'^usuarios/$', 'appxiencias.views.usuarios'),
		url(r'^cliente/$', 'appxiencias.views.cliente'),
		url(r'^usercliente/(\w+)/$', 'appxiencias.views.usercliente'),
		url(r'^userclientecliente/(\w+)/$', 'appxiencias.views.userclientecliente'),
		url(r'^clientecliente/(\w+)/(\w+)/$', 'appxiencias.views.clientecliente'),
		url(r'^lotesms/(\w+)/(\w+)/$', 'appxiencias.views.lotesms'),
		url(r'^upbase/$', 'appxiencias.views.upbase'),
		url(r'^mail/$', 'appxiencias.views.mail'),
		url(r'^externalapp/$', 'appxiencias.views.externalapp'),
		url(r'^appexternas/$', 'appxiencias.views.appexternas'),
		url(r'^externaladd/$', 'appxiencias.views.externaladd'),
		url(r'^blasterindividual/$', 'appxiencias.views.blasterindividual'),
		url(r'^sup/$', 'appxiencias.views.sup'),
		url(r'^age/$', 'appxiencias.views.age'),
		url(r'^externalappedit/$', 'appxiencias.views.externalappedit'),
		url(r'^smsindividual/$', 'appxiencias.views.smsindividual'),
		url(r'^inicio/$', 'appxiencias.views.inicio'),
		url(r'^configuracion/$', 'appxiencias.views.configuracion'),
		url(r'^index/$', 'appxiencias.views.index'),
		url(r'^apisms/$', 'appxiencias.views.apisms'),
		url(r'^enviarsms/(\w+)/$', 'appxiencias.views.enviarsms'),
		url(r'^enviarlotesms/(\w+)/$', 'appxiencias.views.enviarlotesms'),
		url(r'^infolote/(\w+)/$', 'appxiencias.views.infolote'),
		url(r'^run/$', 'appxiencias.views.run'),
		url(r'^actualiza/$', 'appxiencias.views.actualiza'),
		

		url(r'^grupo/(\w+)/$', 'appxiencias.views.grupo'),
		url(r'^agenda$', 'appxiencias.views.agenda'),
		url(r'^grupos/$', 'appxiencias.views.grupos'),
		url(r'^audioapi/$', 'appxiencias.views.audioapi'),
		url(r'^uploadcontacto/$', 'appxiencias.views.uploadcontacto'),

		url(r'^audios/$', 'appxiencias.views.audios'),
		url(r'^agregarlote/$', 'appxiencias.views.agregarlote'),
		url(r'^audio/$', 'appxiencias.views.audio'),
		url(r'^sms/$', 'appxiencias.views.sms'),
		url(r'^campaniasms/$', 'appxiencias.views.campaniasms'),
		url(r'^campania/$', 'appxiencias.views.campania'),
		url(r'^agregarcampania/$', 'appxiencias.views.agregarcampania'),
		url(r'^enviosms/$', 'appxiencias.views.enviosms'),
		url(r'^addgrupo/$', 'appxiencias.views.addgrupo'),
		url(r'^uploadaudio/$', 'appxiencias.views.uploadaudio'),
		url(r'^uploadudioapi/$', 'appxiencias.views.uploadudioapi'),



		url(r'^audiocarga/$', 'appxiencias.views.audiocarga'),
		url(r'^filtros/$', 'appxiencias.views.filtros'),
		url(r'^serviciosapi/$', 'appxiencias.views.serviciosapi'),
		url(r'^uploadblaster/$', 'appxiencias.views.uploadblaster'),
		url(r'^menud/$', 'appxiencias.views.menud'),
		url(r'^estados/(\w+)/(\w+)/$', 'appxiencias.views.estados'),
		url(r'^estadosblaster/(\w+)/(\w+)/$', 'appxiencias.views.estadosblaster'),
		url(r'^proceso/(\w+)/$', 'appxiencias.views.proceso'),
		url(r'^csvfiltro/$', 'appxiencias.views.csvfiltro'),
		url(r'^logear/$', 'appxiencias.views.logear'),
		url(r'^usuario/$', 'appxiencias.views.usuario'),

		# MONITOREO

	    url(r'^monitoreo/$', 'monitoreo.views.dash'),
	    url(r'^llamadas/$', 'monitoreo.views.llamadas'),
	    url(r'^filtermadafaca/$', 'monitoreo.views.filtermadafaca'),
	    url(r'^anexos/$', 'monitoreo.views.anexos'),
	    url(r'^errores/$', 'monitoreo.views.errores'),
	    url(r'^data/$', 'monitoreo.views.data'),
	    url(r'^tipollamadas/$', 'monitoreo.views.tipollamadas'),


	    #CDR

		url(r'^cant/$', 'cdr.views.cant'),
		url(r'^lol/$', 'cdr.views.lol'),
		url(r'^graph/$', 'cdr.views.graph'),
		url(r'^report/$', 'cdr.views.report'),
		url(r'^ingresar/$', 'cdr.views.ingresar'),
		url(r'^salir/$', 'cdr.views.salir'),
		url(r'^cdr/$', 'cdr.views.home'),
		url(r'^field/$', 'cdr.views.field'),
		url(r'^buscar/$', 'cdr.views.buscar'),
		url(r'^campania/$', 'cdr.views.campania'),

		
		)
